# go-setup-playbook.yml
---
- name: Microbenchmark client Setup
  hosts: micro_benchmark
  tasks:
    - name: setup benchmark tool
      shell: |
        git clone https://github.com/martingrambow/GoABS.git $HOME/GoABS
        source ~/.profile
        go version
        cd $HOME/GoABS && go install
      
      args:
        executable: /bin/bash
    - name: clone sut
      shell: |
        source ~/.profile # make sure go is in the path.
        cd $HOME
        git clone https://github.com/VictoriaMetrics/VictoriaMetrics.git latest
        cp -R latest other
        cd other && git checkout {{ VICTORIA_METRICS_VERSION_OTHER }}
        cd .. && cd latest && git checkout {{ VICTORIA_METRICS_VERSION_LATEST }}
        cd ~/
        mkdir -p results
        goabs -c $HOME/abs_config.json -d -o $HOME/results/microbenchmark.csv 
      args:
        executable: /bin/bash
        
- name: retrieve data from client
  import_playbook: retrieve_data_microbenchmark.yml