---
- name: Configure controller
  hosts: controller

  tasks:
    - name: install ansible
      shell: |
         sudo apt update -y
         sudo apt install software-properties-common -y
         sudo apt install ansible -y

    # - name: Run ansible playbook
    #   async: 45
    #   poll: 0
    #   shell: |
    #      ansible-playbook -i hosts_$RUN.yml ./configure_gcp_instances.yml --ssh-common-args='-o StrictHostKeyChecking=no'
    #      sleep 60
    #      ansible-playbook -i hosts_$RUN.yml ./configure_micro_benchmark_client.yml --ssh-common-args='-o StrictHostKeyChecking=no' &
    #      MICRO_PID_1=$!
    #      ansible-playbook -i hosts_$RUN.yml ./configure_application_benchmark_client.yml --ssh-common-args='-o StrictHostKeyChecking=no' &
    #      APPLICATION_PID_2=$!
    #      wait $MICRO_PID_1 $APPLICATION_PID_2

    #   args:
    #     executable: /bin/bash
