---
- name: Configure controller
  hosts: controller
  tasks:
    - name: install ansible
      shell: |
         sudo apt update -y
         sudo apt install software-properties-common -y
         sudo apt install ansible -y
         cd $HOME
         mkdir results

    - name: Creates an entry like
      ansible.builtin.cron:
        name: "a job for reboot"
        special_time: reboot
        job: "/home/benchUser/run_benchmark.sh >> ~/logs.txt 2>&1"

- name: reboot
  hosts: controller
  become: true
  tasks:
    - name: reboot
      shell: sudo reboot
