all:
  vars:
    VICTORIA_METRICS_VERSION_OTHER: v1.108.0
    VICTORIA_METRICS_VERSION_LATEST: v1.109.0
    ansible_user: benchUser
    ansible_ssh_private_key_file: ./bench_dk_id_rsa
    RUN: "{{RUN}}"

application_benchmark:
  hosts:
    "{{VM_APPLICATION_IP}}":
      ansible_connection: ssh
  vars:
    victoria_metrics_data_path: ./vm_data

application_benchmark_client:
  hosts:
    "{{VM_APPLICATION_CLIENT_IP}}":
      ansible_connection: ssh
  vars:
    SUT_IP_AND_PORT_LATEST: "{{VM_APPLICATION_IP}}:8428"
    SUT_IP_AND_PORT_OTHER: "{{VM_APPLICATION_IP}}:8429"