all:
  vars:
    VICTORIA_METRICS_VERSION_OTHER: v1.107.0
    VICTORIA_METRICS_VERSION_LATEST: v1.108.0
    ansible_user: benchUser
    ansible_ssh_private_key_file: ./bench_dk_id_rsa
    RUN: "{{RUN}}"
  
controller:
  hosts:
    "{{VM_CONTROLLER_IP}}":
      ansible_connection: ssh

micro_benchmark:
  hosts:
    "{{VM_MICRO_IP}}":
      ansible_connection: ssh
  vars:
    victoria_metrics_data_path: ./vm_data