---
    - name: Collect data from application benchmark client
      hosts: application_benchmark_client
      gather_facts: no
      remote_user: benchUser
      strategy: free
      become: yes
      tasks:
        - name: Find benchmark all results
          find:
            paths: /home/benchUser/results
            patterns: "*"
          register: log_files

        - name: Collecting results from benchmark client
          fetch:
            flat: yes 
            src: "{{ item.path }}"
            dest: ./results/{{RUN}}/
          with_items: "{{ log_files.files }}"